site_name: Bodywork
copyright: Copyright &copy; 2020-2021 Bodywork Machine Learning Ltd.
repo_url: https://github.com/bodywork-ml/bodywork-core
repo_name: bodywork/bodywork-core
docs_dir: docs
nav:
  - Overview: index.md
  - Install Bodywork: installation.md
  - Setup Kubernetes: kubernetes.md
  - Key Concepts: key_concepts.md
  - User Guide: user_guide.md
  - CLI Reference: cli_reference.md
  - CI/CD for ML: cicd_for_ml.md
  - Deployment Templates: template_projects.md
  - Licensing: licensing.md
  - Contact: contact.md
  - Quickstart Tutorials:
    - Single Stage Batch Workload: quickstart_batch_job.md
    - Single Stage Model Deployment: quickstart_serve_model.md
    - Continuous Training Pipeline: quickstart_ml_pipeline.md
  - Release Notes:
    - Version 2.1.0: release_notes/v2.1.0.md
    - Version 2.0.0: release_notes/v2.0.0.md
    - Version 1.0.0: release_notes/v1.0.0.md
theme: 
  name: material
  features:
    - navigation.instant
    - navigation.sections
  icon:
    logo: octicons/terminal-24
  palette:
    primary: deep purple
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bodywork-ml
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repository/docker/bodyworkml/bodywork-core
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/BodyworkMl
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/bodywork-machine-learning/
