# bodywork - MLOps on Kubernetes.
# Copyright (C) 2020-2021  Bodywork Machine Learning Ltd.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

version: 2.1
jobs:
  test-docs-build:
    docker: 
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Installing Python dependencies
          command: pip install -r requirements.txt
      - run: 
          name: Build docs
          command: mkdocs build
  create-and-push-new-git-tag:
    docker: 
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Tag Git repo.
          command: git tag $(cat VERSION) -f
      - run:
          name: Git push tag.
          command: git push origin $(cat VERSION) -f

workflows:
  version: 2
  docs-pipeline:
    jobs:
      - test-docs-build
      - create-and-push-new-git-tag:
          requires:
            - test-docs-build
          filters:
            branches:
              only: master
